server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://43.138.104.92:3306/foods?characterEncoding=utf-8
      username: root
      password: 123456
